export const YANDEX_LOGIN = {
  YANDEX_CLIENT_ID: 'YANDEX_CLIENT_ID',
  YANDEX_CLIENT_SECRET: 'YANDEX_CLIENT_SECRET',
  YANDEX_CALLBACK_URL: 'YANDEX_CALLBACK_URL',
  FRONTEND_URL: 'FRONTEND_URL',
};

export const COOKIE_MAX_AGE = 7 * 24 * 60 * 60 * 1000;
